### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by mehdichaouch** [jweiland-net/reserve#120]
Hello,

Could you tell me if you have plan any update of this **nice** extension to TYPO3 v12?

Any date for that?

Best,

**Comment by sfroemkenjw** [comment]
Hello @mehdichaouch 

I have just started with the upgrade and all unit and func tests are running again.
You will find current dev version in branch typo3_12_compatibility

I will close this ticket, when we have merged the new release

Stefan

**Comment by mehdichaouch** [comment]
Hello @sfroemkenjw

Ok I get it [typo3_12_compatibility](https://github.com/jweiland-net/reserve/tree/typo3_12_compatibility), thank you.

Mehdi

**Comment by sfroemkenjw** [comment]
@mehdichaouch 

Done
