### ISSUE TITLE
Error revisiting page after ticket order

### ISSUE THREAD

**Issue by jweiland** [jweiland-net/reserve#22]
after ordering (and receiving) tickets, when you go back to the list of time slots in FE an error is thrown:

Oops, an error occurred!
Argument 1 passed to JWeiland\Reserve\Configuration\ExtConf::setBlockMultipleOrdersInSeconds() must be of the type integer, string given, called in /kunden/371571_70794/rp-hosting/5124001/6124001/typo3cms/5124001-pforzheim/development/development-2/releases/20200519104424/web/typo3conf/ext/reserve/Classes/Configuration/ExtConf.php on line 39

**Comment by pascal20997** [comment]
Has been fixed with commit 0efdef16f6078aacb13e2ce14969c14c3e131b9e
