### ISSUE TITLE
Event with open end

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/reserve#61]
Hi,
Thank you very much for the very helpful extension! 
I am working at a university of music where - due to the Corona Pandemic - from autumn on all concerts will have admission restrictions.
In this context I have a suggestion. Sometimes we have concerts whose end is not reliably foreseeable. It would therefore be helpful if the field 'end of event' was not mandatory. If the field would remain empty, there could be written 'Open End' in the FE.

[TYPO3 9.5.20]

-----------------------

BTW: I still have the error described in #57.

**Comment by pascal20997** [comment]
Hey Hobokens and sorry for the late response.
I implemented that feature in current master version. You can now leave that field empty and get 'Open end' in the frontend and mails.
