### ISSUE TITLE
BUG: Output of flash message is cached

### ISSUE THREAD

**Issue by DanielSiepmann** [jweiland-net/reserve#74]
I've tracked the source and created: https://forge.typo3.org/issues/93636
Still the extension needs to adapt.

The concrete scenario:

First flush all caches and open new session (no cookies), then:

1. User creates reservation
2. User receives confirmation mail
3. User cancels reservation via link in confirmation
4. User is redirected to list action with flash message
5. Navigate to create another reservation for same day
6. The cached result with flash message and no form is displayed.

The result is cached, all users that will view the list action will see the message and no form.

**Comment by pascal20997** [comment]
Hey, I fixed that with commit b53b7bcdcd29e2346233f2211b61c4a54be950b3 today. Thanks for the issue :)
