### ISSUE TITLE
jquery.dataTables.min.js

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/reserve#99]
Hi,
I use reserve v1.1. with typo3 10.4.21. The version contains among other things the Javascript library datatables jquery.dataTables.min.js. I know this library to manipulate HTML tables but I don't understand where you use it in the extension. It would be great to get a hint from you.
Regards
Hobokens

**Comment by pascal20997** [comment]
Hey @Hobokens,
DataTables will be used for the frontend management views e.g. for the scanner view or the overview.

**Comment by Hobokens** [comment]
Hey @pascal20997,
rhanks for the explanation.
